# Generated by Django 3.2.9 on 2021-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Indicates alerts has been scheduled to be sent.",
                    ),
                ),
            ],
        ),
    ]
