# Generated by Django 3.2.9 on 2021-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Destination URL back to the main website.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="message",
            field=models.CharField(
                default="",
                help_text="The text message content, not including the URL.",
                max_length=117,
            ),
            preserve_default=False,
        ),
    ]
