# Generated by Django 3.2.9 on 2021-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_event_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date alerts were scheduled to be sent.",
                null=True,
            ),
        ),
    ]
