# Generated by Django 3.2.9 on 2021-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_event_readonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="test_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile number to send a test message.",
                max_length=20,
                null=True,
            ),
        ),
    ]
