# Generated by Django 3.2.9 on 2021-11-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0009_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link_spanish",
            field=models.URLField(
                blank=True,
                help_text="Destination URL back to the main website.",
                null=True,
                verbose_name="Link (Spanish)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="message_spanish",
            field=models.CharField(
                default="",
                help_text="The text message content, not including the URL.",
                max_length=117,
                verbose_name="Message (Spanish)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="link_english",
            field=models.URLField(
                blank=True,
                help_text="Destination URL back to the main website.",
                null=True,
                verbose_name="Link (English)",
            ),
        ),
    ]
