# Generated by Django 3.2.9 on 2021-11-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0011_event_category_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[("n", "Neighborhood Update"), ("v", "Volunteer Opportunity")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="message_english",
            field=models.CharField(
                help_text="The text message content, not including the URL. (224 characters)",
                max_length=224,
                verbose_name="Message (English)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="message_spanish",
            field=models.CharField(
                help_text="The text message content, not including the URL. (224 characters)",
                max_length=224,
                verbose_name="Message (Spanish)",
            ),
        ),
    ]
