# Generated by Django 3.2.9 on 2021-11-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0012_event_longer_sms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="link_english",
            field=models.URLField(
                blank=True,
                help_text="Optional URL to get additional information about this alert.",
                null=True,
                verbose_name="Link (English)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="link_spanish",
            field=models.URLField(
                blank=True,
                help_text="Optional URL to get additional information about this alert.",
                null=True,
                verbose_name="Link (Spanish)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="message_english",
            field=models.CharField(
                help_text="The text message content, not including the URL. [224 characters]",
                max_length=224,
                verbose_name="Message (English)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="message_spanish",
            field=models.CharField(
                help_text="The text message content, not including the URL. [224 characters]",
                max_length=224,
                verbose_name="Message (Spanish)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="test_number",
            field=models.CharField(
                blank=True,
                help_text="Optional mobile number to send a test message.",
                max_length=20,
                null=True,
            ),
        ),
    ]
