# Generated by Django 3.2.9 on 2021-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0013_update_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="sent_count",
            field=models.IntegerField(
                default=0,
                editable=False,
                help_text="Number of residents who have received this alert.",
                verbose_name="Recipients",
            ),
        ),
    ]
