# Generated by Django 3.2.9 on 2021-11-06 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="joined_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when user requested a login code.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="alerted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when user was last sent an alert.",
            ),
        ),
    ]
