# Generated by Django 3.2.9 on 2021-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_joined_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="valid",
            field=models.BooleanField(
                default=None,
                help_text="Indicates a user has entered a valid login code.",
                null=True,
            ),
        ),
    ]
