# Generated by Django 3.2.9 on 2021-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish")],
                default="en",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
