# Generated by Django 3.2.9 on 2021-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="neighborhood_updates",
            field=models.BooleanField(
                default=False, verbose_name="Neighborhood Updates"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="volunteer_opportunities",
            field=models.BooleanField(
                default=False, verbose_name="Volunteer Opportunities"
            ),
            preserve_default=False,
        ),
    ]
