# Generated by Django 3.2.9 on 2021-11-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="neighborhood_updates",
            field=models.BooleanField(
                default=False, verbose_name="Neighborhood Updates"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="volunteer_opportunities",
            field=models.BooleanField(
                default=False, verbose_name="Volunteer Opportunities"
            ),
        ),
    ]
