# Generated by Django 3.2.9 on 2021-11-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile_change_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español")], max_length=2
            ),
        ),
    ]
