# Generated by Django 3.2.9 on 2021-11-07 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="received_count",
            field=models.IntegerField(
                default=0, help_text="Number of alerts sent to this user."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when user was last updated.",
            ),
        ),
    ]
