# Generated by Django 3.2.9 on 2021-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_profile_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español")],
                max_length=2,
                verbose_name="Language Preference",
            ),
        ),
    ]
